// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSaving struct {
	UserID string `json:"userId"`
}

type NewSavingDetail struct {
	SavingID     int    `json:"savingId"`
	SavingAmount int    `json:"savingAmount"`
	SavingDate   string `json:"savingDate"`
	Note         string `json:"note"`
}

type NewTodo struct {
	Text   *string `json:"text"`
	UserID string  `json:"userId"`
}

type SavingsDetail struct {
	ID           string `json:"id"`
	SavingID     int    `json:"saving_id"`
	SavingAmount int    `json:"saving_amount"`
	SavingDate   string `json:"saving_date"`
	Note         string `json:"note"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SavingsDetailsFilter struct {
	SavingsID int `json:"savings_id"`
	First     int `json:"first"`
	Last      int `json:"last"`
}
